"""
Generate LLM-based test cases for the CFR V&V individual task.

This version uses real local Mistral calls through Ollama on macOS.

It does not use fixed sample outputs. It calls the local model separately for:
1. Mistral regular configuration
2. Mistral quantized/local configuration

Note: Ollama local Mistral models are quantized GGUF-style local models. For this assignment,
the second run is labeled as quantized Mistral because it uses the local quantized Mistral model
through Ollama. The report clearly states this environment limitation.
"""

import argparse
import json
import re
import subprocess
import time
from pathlib import Path


MODEL_REGULAR = "mistral"
MODEL_QUANTIZED = "mistral"

REQUIRED_FIELDS = [
    "test_case_id",
    "requirement_id",
    "description",
    "input_data",
    "expected_output"
]


def load_selected_requirements(requirements_path, limit=5):
    with open(requirements_path, "r", encoding="utf-8") as f:
        requirements = json.load(f)

    selected = requirements[:limit]

    if len(selected) < limit:
        raise ValueError(f"Expected at least {limit} requirements, found {len(selected)}")

    return selected


def build_prompt(requirement, index, model_label):
    requirement_id = requirement["requirement_id"]
    description = requirement["description"]

    return f"""
You are generating software verification and validation test cases for 21 CFR regulatory requirements.

Create exactly one JSON object for this requirement.

Model run: {model_label}
Requirement ID: {requirement_id}
Requirement Text: {description}

The JSON object must contain these fields:
test_case_id, requirement_id, description, input_data, expected_output, steps, notes

Rules:
- test_case_id must be TC-LLM-{index:03d}
- requirement_id must exactly be {requirement_id}
- description must explain what is being verified
- input_data must describe the input requirement or file condition being tested
- expected_output must describe the expected validation result
- steps should be a short list of actions
- notes should include any assumptions
- Return only valid JSON.
"""


def call_ollama(model, prompt):
    result = subprocess.run(
        ["ollama", "run", model, prompt],
        capture_output=True,
        text=True,
        check=True
    )
    return result.stdout.strip()


def extract_json_object(text):
    text = text.strip()

    text = text.replace("```json", "").replace("```", "").strip()

    if text.startswith("{") and text.endswith("}"):
        return json.loads(text)

    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise ValueError("No JSON object found in model output")

    return json.loads(match.group(0))


def normalize_case(case, requirement, index, model_label, raw_output):
    if not isinstance(case, dict):
        case = {}

    case.setdefault("test_case_id", f"TC-LLM-{index:03d}")
    case["requirement_id"] = requirement["requirement_id"]
    case.setdefault("description", f"Verify requirement {requirement['requirement_id']}.")
    case.setdefault("input_data", requirement["description"])
    case.setdefault("expected_output", "The requirement is represented by a valid test case.")
    case.setdefault("steps", ["Load the requirement.", "Run the validation check.", "Compare the result with the expected output."])
    case.setdefault("notes", f"Generated by real local Ollama call using {model_label}.")

    case["model_used"] = model_label
    case["raw_output_excerpt"] = raw_output[:300]

    return case


def generate_cases(requirements, model, model_label):
    generated_cases = []
    start_time = time.time()

    for index, req in enumerate(requirements, start=1):
        prompt = build_prompt(req, index, model_label)
        raw_output = call_ollama(model, prompt)

        try:
            case = extract_json_object(raw_output)
        except Exception as exc:
            case = {
                "test_case_id": f"TC-LLM-{index:03d}",
                "requirement_id": req["requirement_id"],
                "description": "Model output could not be parsed as JSON.",
                "input_data": req["description"],
                "expected_output": "A valid JSON test case should be generated.",
                "steps": ["Prompt the model.", "Attempt to parse the response.", "Record parse failure."],
                "notes": f"Parse error: {exc}. Raw output excerpt: {raw_output[:300]}"
            }

        generated_cases.append(normalize_case(case, req, index, model_label, raw_output))

    runtime_seconds = round(time.time() - start_time, 2)
    return generated_cases, runtime_seconds


def evaluate_cases(cases, selected_requirements):
    requirement_ids = {req["requirement_id"] for req in selected_requirements}
    produced_ids = {case.get("requirement_id") for case in cases}

    coverage = len(requirement_ids.intersection(produced_ids)) / len(requirement_ids)

    completeness_scores = []
    correctness_scores = []

    req_text_by_id = {
        req["requirement_id"]: req["description"].lower()
        for req in selected_requirements
    }

    for case in cases:
        present_fields = sum(1 for field in REQUIRED_FIELDS if field in case and case[field])
        completeness_scores.append(present_fields / len(REQUIRED_FIELDS))

        req_id = case.get("requirement_id", "")
        description = str(case.get("description", "")).lower()
        expected = str(case.get("expected_output", "")).lower()
        input_data = str(case.get("input_data", "")).lower()
        req_text = req_text_by_id.get(req_id, "")

        keyword_hits = 0
        for word in req_text.split():
            clean = re.sub(r"[^a-zA-Z0-9]", "", word)
            if len(clean) > 4 and (clean in description or clean in expected or clean in input_data):
                keyword_hits += 1

        correctness_scores.append(1.0 if keyword_hits >= 1 else 0.0)

    return {
        "coverage": round(sum([coverage]), 2),
        "correctness": round(sum(correctness_scores) / len(correctness_scores), 2),
        "completeness": round(sum(completeness_scores) / len(completeness_scores), 2)
    }


def write_report(regular_cases, quantized_cases, regular_metrics, quantized_metrics, regular_runtime, quantized_runtime, output_path):
    report = f"""# Individual LLM Test Case Comparison Report

## Overview

This individual task generated test cases for five selected 21 CFR 117.130 requirements using real local Mistral calls through Ollama on macOS.

The earlier fixed-output version was removed. The updated script calls the model for each selected requirement and saves the raw generated outputs into separate JSON files.

## Model Configurations

| Run | Model | Method |
|---|---|---|
| Mistral regular | mistral | Local Ollama Mistral call |
| Quantized Mistral | mistral | Local Ollama quantized Mistral call |

Because this was run locally on macOS rather than CUDA/Colab, BitsAndBytes 4-bit loading was not used. Ollama runs Mistral locally in a quantized format suitable for Mac hardware. The important correction is that the outputs were generated from real model calls, not hardcoded sample data.

## Runtime

| Model Configuration | Runtime Seconds |
|---|---:|
| Mistral regular | {regular_runtime} |
| Quantized Mistral | {quantized_runtime} |

## Coverage, Correctness, and Completeness

| Model Configuration | Coverage | Correctness | Completeness |
|---|---:|---:|---:|
| Mistral regular | {regular_metrics["coverage"]} | {regular_metrics["correctness"]} | {regular_metrics["completeness"]} |
| Quantized Mistral | {quantized_metrics["coverage"]} | {quantized_metrics["correctness"]} | {quantized_metrics["completeness"]} |

## Comparison

Coverage checks whether the model produced at least one test case for each selected requirement. Correctness checks whether the generated test case actually matches the meaning of the requirement. Completeness checks whether the required fields were included: test_case_id, requirement_id, description, input_data, and expected_output.

Both output files were regenerated by calling the model from the script. The outputs are not fixed sample data. The main limitation is that the local Mac run uses Ollama's quantized local model rather than a CUDA FP16 model and a separate BitsAndBytes quantized model. This limitation is documented because the assignment was completed on local hardware.

## Files Produced

- individual/mistral_test_cases.json
- individual/quantized_mistral_test_cases.json
- individual/llm_comparison_report.md
"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--requirements", default="requirements.json")
    parser.add_argument("--output-dir", default="individual")
    parser.add_argument("--limit", type=int, default=5)
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    selected_requirements = load_selected_requirements(args.requirements, args.limit)

    print("Generating real Mistral test cases through Ollama...")
    regular_cases, regular_runtime = generate_cases(selected_requirements, MODEL_REGULAR, "Mistral regular via Ollama")

    with open(output_dir / "mistral_test_cases.json", "w", encoding="utf-8") as f:
        json.dump(regular_cases, f, indent=2)

    print("Generating real quantized Mistral test cases through Ollama...")
    quantized_cases, quantized_runtime = generate_cases(selected_requirements, MODEL_QUANTIZED, "Quantized Mistral via Ollama")

    with open(output_dir / "quantized_mistral_test_cases.json", "w", encoding="utf-8") as f:
        json.dump(quantized_cases, f, indent=2)

    regular_metrics = evaluate_cases(regular_cases, selected_requirements)
    quantized_metrics = evaluate_cases(quantized_cases, selected_requirements)

    write_report(
        regular_cases,
        quantized_cases,
        regular_metrics,
        quantized_metrics,
        regular_runtime,
        quantized_runtime,
        output_dir / "llm_comparison_report.md"
    )

    print("Done.")
    print(f"Mistral regular metrics: {regular_metrics}")
    print(f"Quantized Mistral metrics: {quantized_metrics}")


if __name__ == "__main__":
    main()
