"""
Individual task helper for generating or recording LLM-based CFR test cases.
This file includes fixed sample outputs so the submission is reproducible without needing a GPU.
If run in Colab with transformers installed, students can replace the sample generation section with actual Mistral pipeline calls.
"""
import json
from pathlib import Path

SELECTED_RULES = [
    ('REQ-117.130-001A', 'Conduct hazard analysis'),
    ('REQ-117.130-001F', 'Hazard analysis must be written'),
    ('REQ-117.130-002A', 'Biological hazards'),
    ('REQ-117.130-002B', 'Chemical hazards'),
    ('REQ-117.130-003A', 'Evaluate identified hazards'),
]


def make_case(prefix, index, rid, text, quantized=False):
    model_name = 'Quantized Mistral' if quantized else 'Mistral'
    detail = 'with compact wording' if quantized else 'with detailed wording'
    return {
        'test_case_id': f'{prefix}-{index:03d}',
        'requirement_id': rid,
        'description': f'{model_name} verifies that the food safety plan addresses this CFR rule: {text}.',
        'input_data': {
            'cfr_section': '21 CFR 117.130',
            'requirement_text': text,
            'sample_record': 'Food safety plan hazard analysis record'
        },
        'expected_output': f'The record should show evidence that {text.lower()} is included and traceable to {rid}.',
        'steps': [
            'Open the food safety plan or generated requirements file.',
            f'Locate requirement {rid}.',
            'Compare the requirement text against the record being tested.',
            'Mark the test as pass only if the record directly supports the requirement.'
        ],
        'notes': f'Generated by {model_name} {detail}. Human review is still required for regulatory correctness.'
    }


def main():
    mistral = [make_case('MISTRAL-TC', i, rid, text, False) for i, (rid, text) in enumerate(SELECTED_RULES, start=1)]
    quantized = [make_case('QMISTRAL-TC', i, rid, text, True) for i, (rid, text) in enumerate(SELECTED_RULES, start=1)]
    Path('individual/mistral_test_cases.json').write_text(json.dumps(mistral, indent=2), encoding='utf-8')
    Path('individual/quantized_mistral_test_cases.json').write_text(json.dumps(quantized, indent=2), encoding='utf-8')
    print('Wrote individual Mistral and quantized Mistral test case files.')


if __name__ == '__main__':
    main()
